[package]
name = "merkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
sha3 = "0.10.6"
thiserror = "1.0.40"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false

[profile.bench]
debug = true
